//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForTheCommonGood.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ForTheCommonGood.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Ambox_notice {
            get {
                object obj = ResourceManager.GetObject("Ambox_notice", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Checker_16x16 {
            get {
                object obj = ResourceManager.GetObject("Checker_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # For the Common Good
        ///# Language file for English
        ///
        ///# To ensure the highest quality of translation, please read the LOCALIZATION NOTE lines.
        ///# You do not need to translate lines beginning with the # symbol.
        ///
        ///LanguageCode=en
        ///
        ///# Main window
        ///OriginalFileName_TextBox=&amp;Name:
        ///Go_Button=&amp;Go
        ///RandomFile_Button=&amp;Random file
        ///# LOCALIZATION NOTE: this should have the same access key as &quot;RandomFile_Button&quot;
        ///NextFileInList_Button=Next file f&amp;rom list
        ///OtherSource_Option=&amp;Other source...
        ///Settings_Button=&amp;Setti [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultStrings {
            get {
                return ResourceManager.GetString("DefaultStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # For the Common Good
        ///# Local wiki data for English Wikipedia (built into FtCG)
        ///
        ///# See http://en.wikipedia.org/wiki/User:This,_that_and_the_other/For_the_Common_Good/Local_wiki_data
        ///# for a template you can use to create your own local wiki data files.
        ///
        ///LocalDomain=en.wikipedia (Default)
        ///
        ///LocalFtcgPage=WP:FTCG
        ///
        ///Category1=Copy to Wikimedia Commons
        ///Category2=Copy to Wikimedia Commons (bot-assessed)
        ///Category3=Move to Commons Priority Candidates
        ///DefaultCategory=3
        ///
        ///# These are ignored on enwiki at [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string en_wikipedia {
            get {
                return ResourceManager.GetString("en_wikipedia", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Imbox_content {
            get {
                object obj = ResourceManager.GetObject("Imbox_content", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Information_icon4 {
            get {
                object obj = ResourceManager.GetObject("Information_icon4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Internet_link_02 {
            get {
                object obj = ResourceManager.GetObject("Internet_link_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Magnifying_glass_icon {
            get {
                object obj = ResourceManager.GetObject("Magnifying_glass_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] zoomin_cur {
            get {
                object obj = ResourceManager.GetObject("zoomin_cur", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
