//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForTheCommonGood.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ForTheCommonGood.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Ambox_notice {
            get {
                object obj = ResourceManager.GetObject("Ambox_notice", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Checker_16x16 {
            get {
                object obj = ResourceManager.GetObject("Checker_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LanguageCode=en
        ///
        ///# Main window
        ///OriginalFileName_TextBox=&amp;Name:
        ///Go_Button=&amp;Go
        ///RandomFile_Button=&amp;Random file
        ///# LOCALIZATION NOTE: this should have the same access key as &quot;RandomFile_Button&quot;
        ///NextFileInList_Button=Next file f&amp;rom list
        ///CopyToWikimediaCommons_Option=Category:Copy to Wikimedia Commons
        ///CopyToWikimediaCommonsBotAssessed_Option=Category:Copy to Wikimedia Commons (bot-assessed)
        ///MoveToCommonsPriority_Option=Category:Move to Commons Priority Candidates
        ///OtherSource_Option=&amp;Other source...
        ///Se [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultStrings {
            get {
                return ResourceManager.GetString("DefaultStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # For the Common Good
        ///# Local wiki data for English Wikipedia
        ///
        ///LocalDomain=en.wikipedia
        ///
        ///# Three preset categories
        ///Category1=Copy to Wikimedia Commons
        ///Category2=Copy to Wikimedia Commons (bot-assessed)
        ///Category3=Move to Commons Priority Candidates
        ///Default=3
        ///
        ///# IMPORTANT: All entries from here onwards are treated as regular expressions.
        ///# For normal text entry, this should not be a problem, but when using
        ///# symbols like ( ) [ ] ? * + | etc., please prefix with a backslash: \( \[ etc.
        ///
        ///# Local  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string en_wikipedia {
            get {
                return ResourceManager.GetString("en_wikipedia", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Imbox_content {
            get {
                object obj = ResourceManager.GetObject("Imbox_content", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Information_icon4 {
            get {
                object obj = ResourceManager.GetObject("Information_icon4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Throbber_dark {
            get {
                object obj = ResourceManager.GetObject("Throbber_dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] zoomin_cur {
            get {
                object obj = ResourceManager.GetObject("zoomin_cur", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
